# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Gomake < Formula
  desc "Redesign of GNU Make (Makefile) oriented towards project management and command uniformisation among all your projects."
  homepage "http://github.com/efimovalex/gomake"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/fimovalex/gomake/releases/download/{ .Tag }}/gomake_1.0.2_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "c7bc82aaad8a496a1b3740d8f2db96af388683bdba3b7646e69aeb99a38f06b6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/fimovalex/gomake/releases/download/{ .Tag }}/gomake_1.0.2_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "da588d7327558946605e6708c3ad4eb382fcb0801a0a7c911706a2d44c14df35"
    end
  end
  
  head "http://github.com/fimovalex/gomake.git"
  ...
  
  depends_on "git"

  def install
    bin.install "program"
    ...
  end

  def caveats; <<~EOS
    Usage: gomake [options] [target] ...
    
    Options:
    
      -f FILE, --file=path/to/file.yml 	Read pointed file as a the targets file.
      -v, --version 						        Prints the version.
      -h, --help                    		Prints this message."
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
...

  EOS
  end

  test do
    system "#{bin}/gomake --version"
    ...
  end
end
