# This file was generated by GoReleaser. DO NOT EDIT.
class Gomake < Formula
  desc "Redesign of GNU Make (Makefile) oriented towards project management and command uniformisation among all your projects."
  homepage "http://github.com/efimovalex/gomake"
  version "1.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v1.0.5/gomake_1.0.5_Darwin_x86_64.tar.gz"
    sha256 "c46e5f57d4848dd12374a206be8922a342258b6568f131a064c05c49e84acc39"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v1.0.5/gomake_1.0.5_Linux_x86_64.tar.gz"
      sha256 "00e7837f17f2b0531802ec4be2d04e44b4ef55a9b807d696f2606c7e5d9d4902"
    end
  end
  
  depends_on "git"

  def install
    bin.install "gomake"
  end

  def caveats; <<~EOS
    Usage: gomake [options] [target] ...
    
    Options:
    
      -f FILE, --file=path/to/file.yml 	Read pointed file as a the targets file.
      -v, --version 						        Prints the version.
      -h, --help                    		Prints this message."
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>

  EOS
  end

  test do
    system "#{bin}/gomake --version"
  end
end
