# This file was generated by GoReleaser. DO NOT EDIT.
class Gomake < Formula
  desc "Redesign of GNU Make (Makefile) oriented towards project management and command uniformisation among all your projects."
  homepage "http://github.com/efimovalex/gomake"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/efimovalex/gomake/releases/download/v1.0.2/gomake_1.0.2_Darwin_x86_64.tar.gz"
    sha256 "8f3a71aa7283e5aee495737ee296a472b5e5fca07485349b6187ca1bc3515ede"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/efimovalex/gomake/releases/download/v1.0.2/gomake_1.0.2_Linux_x86_64.tar.gz"
      sha256 "f491f2f83dcefa1b33d960cabdddf9ff51bc673067a95c0feda8fb42b33c618c"
    end
  end
  
  depends_on "git"

  def install
    bin.install "gomake"
  end

  def caveats; <<~EOS
    Usage: gomake [options] [target] ...
    
    Options:
    
      -f FILE, --file=path/to/file.yml 	Read pointed file as a the targets file.
      -v, --version 						        Prints the version.
      -h, --help                    		Prints this message."
  EOS
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>

  EOS
  end

  test do
    system "#{bin}/gomake --version"
  end
end
